[01/Jul/2022 00:34:14.610]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 00:36:08.604]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 00:36:09.384]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 00:37:52.178]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 00:37:52.977]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 01:04:41.842]INFO [django.utils.autoreload:251] /usr/src/app/api/urls.py changed, reloading.
[01/Jul/2022 01:04:42.552]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 01:07:17.937]INFO [django.server:161] "GET /admin/ HTTP/1.1" 200 3983
[01/Jul/2022 01:07:17.963]INFO [django.server:161] "GET /static/admin/css/base.css HTTP/1.1" 200 19513
[01/Jul/2022 01:07:17.963]INFO [django.server:161] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2271
[01/Jul/2022 01:07:17.964]INFO [django.server:161] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18545
[01/Jul/2022 01:07:18.016]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 01:07:18.016]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 01:07:18.122]INFO [django.server:161] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[01/Jul/2022 01:07:18.123]INFO [django.server:161] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[01/Jul/2022 01:07:18.123]INFO [django.server:161] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[01/Jul/2022 01:07:18.153]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 01:07:18.153]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 01:07:19.154]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 01:07:19.154]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 01:07:21.857]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 4952
[01/Jul/2022 01:07:21.873]INFO [django.server:161] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6874
[01/Jul/2022 01:07:21.881]INFO [django.server:161] "GET /static/admin/js/urlify.js HTTP/1.1" 200 7902
[01/Jul/2022 01:07:21.882]INFO [django.server:161] "GET /static/admin/js/core.js HTTP/1.1" 200 5698
[01/Jul/2022 01:07:21.882]INFO [django.server:161] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 5984
[01/Jul/2022 01:07:21.883]INFO [django.server:161] "GET /static/admin/js/actions.js HTTP/1.1" 200 7664
[01/Jul/2022 01:07:21.886]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 01:07:21.888]INFO [django.server:161] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[01/Jul/2022 01:07:21.889]INFO [django.server:161] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[01/Jul/2022 01:07:21.932]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 01:07:21.932]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 01:07:22.937]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 01:07:22.937]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 01:07:24.445]INFO [django.server:161] "GET /admin/core/campaing/add/ HTTP/1.1" 200 14597
[01/Jul/2022 01:07:24.463]INFO [django.server:161] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[01/Jul/2022 01:07:24.463]INFO [django.server:161] "GET /static/admin/css/forms.css HTTP/1.1" 200 8804
[01/Jul/2022 01:07:24.464]INFO [django.server:161] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19634
[01/Jul/2022 01:07:24.464]INFO [django.server:161] "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
[01/Jul/2022 01:07:24.468]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 01:07:24.477]INFO [django.server:161] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[01/Jul/2022 01:07:24.507]INFO [django.server:161] "GET /static/admin/css/widgets.css HTTP/1.1" 200 11097
[01/Jul/2022 01:07:24.539]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 01:07:24.540]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 01:07:24.540]INFO [django.server:161] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[01/Jul/2022 01:07:25.540]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 01:07:25.540]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 01:16:23.485]WARNING [django.request:224] Unauthorized: /api/v1/user/campaing
[01/Jul/2022 01:16:23.486]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 401 38
[01/Jul/2022 01:16:29.422]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 11
[01/Jul/2022 01:21:23.766]INFO [django.utils.autoreload:251] /usr/src/app/campaings/urls.py changed, reloading.
[01/Jul/2022 01:21:24.505]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 01:34:58.152]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 01:34:58.935]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 01:35:49.907]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 01:35:50.676]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 01:36:35.314]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ValueError is not JSON serializable
[01/Jul/2022 01:36:35.798]WARNING [django.request:224] Bad Request: /api/v1/user
[01/Jul/2022 01:36:36.107]WARNING [django.request:224] Bad Request: /api/v1/user
[01/Jul/2022 22:20:39.019]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 22:20:59.774]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[01/Jul/2022 22:20:59.775]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 96893
[01/Jul/2022 22:46:03.449]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[01/Jul/2022 22:46:03.450]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 96893
[01/Jul/2022 22:46:05.290]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[01/Jul/2022 22:46:05.290]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 96893
[01/Jul/2022 22:47:03.286]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 22:47:04.001]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 22:47:12.090]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[01/Jul/2022 22:47:12.091]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 96893
[01/Jul/2022 22:49:21.544]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 22:49:22.242]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 22:49:25.294]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[01/Jul/2022 22:49:25.295]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 96893
[01/Jul/2022 22:52:06.034]INFO [django.server:161] "GET /admin/ HTTP/1.1" 200 3983
[01/Jul/2022 22:52:06.224]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:52:06.225]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:52:06.229]INFO [django.server:161] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[01/Jul/2022 22:52:06.230]INFO [django.server:161] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[01/Jul/2022 22:52:06.230]INFO [django.server:161] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[01/Jul/2022 22:52:06.259]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:52:06.260]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:52:07.259]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:52:07.259]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:52:08.503]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 4952
[01/Jul/2022 22:52:08.524]INFO [django.server:161] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[01/Jul/2022 22:52:08.526]INFO [django.server:161] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[01/Jul/2022 22:52:08.529]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 22:52:08.581]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:52:08.581]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:52:09.585]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:52:09.585]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:54:02.706]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 22:54:03.433]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 22:54:57.634]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 22:54:58.337]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 22:55:34.169]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 22:55:34.868]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 22:56:44.383]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 22:57:18.391]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 22:57:35.074]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 302 0
[01/Jul/2022 22:57:35.096]INFO [django.server:161] "GET /admin/login/?next=/admin/core/campaing/ HTTP/1.1" 200 2239
[01/Jul/2022 22:57:35.153]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:35.154]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:36.158]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:36.159]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:37.773]INFO [django.server:161] "POST /admin/login/?next=/admin/core/campaing/ HTTP/1.1" 302 0
[01/Jul/2022 22:57:37.794]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 4952
[01/Jul/2022 22:57:37.820]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 22:57:37.905]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:37.905]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:38.915]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:38.916]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:39.990]INFO [django.server:161] "GET /admin/core/user/ HTTP/1.1" 200 8676
[01/Jul/2022 22:57:40.011]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 22:57:40.046]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:40.047]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:41.053]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:41.054]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:43.267]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 4952
[01/Jul/2022 22:57:43.287]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 22:57:43.313]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:43.313]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:44.319]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:44.319]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:44.938]INFO [django.server:161] "GET /admin/core/campaing/add/ HTTP/1.1" 200 14631
[01/Jul/2022 22:57:44.961]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 22:57:45.002]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:45.002]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:57:46.012]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 22:57:46.012]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 22:58:08.319]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[01/Jul/2022 22:58:08.320]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 96893
[01/Jul/2022 23:03:47.523]INFO [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 201 126
[01/Jul/2022 23:04:09.173]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 4952
[01/Jul/2022 23:04:09.203]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:04:09.250]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:04:09.250]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:04:10.257]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:04:10.258]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:04:15.347]INFO [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 201 126
[01/Jul/2022 23:04:43.631]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 4952
[01/Jul/2022 23:04:43.662]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:04:43.717]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:04:43.717]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:04:44.469]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 4952
[01/Jul/2022 23:04:44.487]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:04:44.518]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:04:44.519]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:04:46.048]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:04:46.048]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:05:44.821]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[01/Jul/2022 23:05:44.822]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 99256
[01/Jul/2022 23:07:01.220]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.9/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
[01/Jul/2022 23:07:01.221]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 99196
[01/Jul/2022 23:07:43.840]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:07:44.580]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:08:01.724]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:08:07.272]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:08:07.272]WARNING [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 400 58
[01/Jul/2022 23:10:13.409]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:10:14.133]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:10:22.296]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/app/campaings/views.py", line 37, in create
    created = Campaing.create(request)
  File "/usr/src/app/core/campaing.py", line 57, in create
    created = cls.objects.create(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1415, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1358, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1359, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1300, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 842, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1271, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1266, in get_prep_value
    return self.to_python(value)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1228, in to_python
    parsed = parse_date(value)
  File "/usr/local/lib/python3.9/site-packages/django/utils/dateparse.py", line 75, in parse_date
    match = date_re.match(value)
TypeError: expected string or bytes-like object
[01/Jul/2022 23:10:22.298]ERROR [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 500 186604
[01/Jul/2022 23:12:13.228]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:12:13.935]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:13:24.415]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:13:25.096]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:13:55.815]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:13:56.501]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:14:34.049]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:14:34.050]WARNING [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 400 58
[01/Jul/2022 23:15:55.669]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:15:56.289]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:16:01.461]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:16:01.462]WARNING [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 400 58
[01/Jul/2022 23:18:08.481]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:18:09.104]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:18:14.526]INFO [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 201 36
[01/Jul/2022 23:18:20.189]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 6106
[01/Jul/2022 23:18:20.225]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:18:20.376]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:18:20.376]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:18:21.388]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:18:21.389]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:18:21.991]INFO [django.server:161] "GET /admin/core/campaing/1/change/ HTTP/1.1" 200 15384
[01/Jul/2022 23:18:22.015]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:18:22.056]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:18:22.057]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:18:23.065]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:18:23.065]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:18:59.056]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:18:59.689]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:21:00.561]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:21:01.182]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:21:48.526]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:22:41.036]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:22:45.329]INFO [django.server:161] "GET /admin/core/user/ HTTP/1.1" 302 0
[01/Jul/2022 23:22:45.343]INFO [django.server:161] "GET /admin/login/?next=/admin/core/user/ HTTP/1.1" 200 2231
[01/Jul/2022 23:22:45.393]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:22:45.393]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:22:46.397]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:22:46.397]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:22:47.987]INFO [django.server:161] "POST /admin/login/?next=/admin/core/user/ HTTP/1.1" 302 0
[01/Jul/2022 23:22:48.016]INFO [django.server:161] "GET /admin/core/user/ HTTP/1.1" 200 8676
[01/Jul/2022 23:22:48.037]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:22:48.078]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:22:48.078]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:22:49.089]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:22:49.090]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:22:50.072]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 4952
[01/Jul/2022 23:22:50.093]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:22:50.120]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:22:50.120]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:22:51.127]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:22:51.128]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:22:54.472]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:22:54.473]WARNING [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 400 264
[01/Jul/2022 23:23:30.228]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:23:30.228]WARNING [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 400 308
[01/Jul/2022 23:23:45.942]INFO [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 201 36
[01/Jul/2022 23:23:50.163]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 6106
[01/Jul/2022 23:23:50.194]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:23:50.245]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:23:50.246]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:23:51.244]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:23:51.245]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:23:51.265]INFO [django.server:161] "GET /admin/core/campaing/1/change/ HTTP/1.1" 200 15387
[01/Jul/2022 23:23:51.288]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:23:51.332]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:23:51.333]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:23:52.340]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:23:52.341]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:24:30.494]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:24:30.494]WARNING [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 400 283
[01/Jul/2022 23:24:41.578]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:24:41.578]WARNING [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 400 281
[01/Jul/2022 23:24:56.992]INFO [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 201 36
[01/Jul/2022 23:24:59.470]INFO [django.server:161] "GET /admin/core/campaing/ HTTP/1.1" 200 6317
[01/Jul/2022 23:24:59.504]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:24:59.540]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:24:59.540]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:25:00.548]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:25:00.548]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:25:03.361]INFO [django.server:161] "GET /admin/core/campaing/2/change/ HTTP/1.1" 200 15375
[01/Jul/2022 23:25:03.383]INFO [django.server:161] "GET /admin/jsi18n/ HTTP/1.1" 200 3195
[01/Jul/2022 23:25:03.426]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:25:03.426]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:25:04.435]WARNING [django.request:224] Not Found: /favicon.ico
[01/Jul/2022 23:25:04.435]WARNING [django.server:161] "GET /favicon.ico HTTP/1.1" 404 2556
[01/Jul/2022 23:25:28.288]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 11
[01/Jul/2022 23:26:00.358]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 11
[01/Jul/2022 23:27:25.583]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:27:26.210]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:27:39.226]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 11
[01/Jul/2022 23:47:56.437]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:47:57.064]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:48:01.905]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 11
[01/Jul/2022 23:48:02.975]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 11
[01/Jul/2022 23:48:03.902]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 11
[01/Jul/2022 23:50:54.440]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:50:55.155]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:51:02.795]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 11
[01/Jul/2022 23:56:31.380]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:56:32.018]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:56:53.377]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:56:54.006]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:56:56.818]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:56:56.818]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:57:07.031]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:57:07.031]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:57:25.619]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[01/Jul/2022 23:57:26.249]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:57:41.638]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:57:42.273]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:57:47.438]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:57:47.439]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:57:49.412]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:57:49.412]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:57:52.090]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:57:52.090]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:58:14.939]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:58:15.566]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:58:17.772]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:58:17.772]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:58:40.083]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:58:40.706]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:58:58.117]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:58:58.746]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:59:01.384]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[01/Jul/2022 23:59:01.385]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75487
[01/Jul/2022 23:59:21.261]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:59:21.899]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:59:24.751]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:59:24.751]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:59:26.769]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:59:26.769]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:59:41.365]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:59:41.988]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:59:44.494]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:59:44.494]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[01/Jul/2022 23:59:55.306]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[01/Jul/2022 23:59:55.936]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[01/Jul/2022 23:59:57.525]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[01/Jul/2022 23:59:57.525]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 78
[02/Jul/2022 00:00:11.311]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:00:11.939]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:00:13.688]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:00:13.688]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 78
[02/Jul/2022 00:01:41.282]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:01:41.909]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:01:46.621]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[02/Jul/2022 00:01:46.622]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75487
[02/Jul/2022 00:02:58.207]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:02:58.845]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:03:04.359]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[02/Jul/2022 00:03:04.359]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75487
[02/Jul/2022 00:05:41.242]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:05:41.877]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:05:49.053]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[02/Jul/2022 00:05:49.054]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75487
[02/Jul/2022 00:06:07.439]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:06:08.057]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:06:13.559]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[02/Jul/2022 00:06:13.560]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75487
[02/Jul/2022 00:06:23.565]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[02/Jul/2022 00:06:23.566]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75487
[02/Jul/2022 00:06:50.813]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:06:51.441]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:06:57.605]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:06:57.605]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 58
[02/Jul/2022 00:07:04.071]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:07:04.071]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 58
[02/Jul/2022 00:07:43.343]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:07:43.963]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:07:52.504]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:07:52.505]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[02/Jul/2022 00:08:06.174]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[02/Jul/2022 00:08:06.175]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75614
[02/Jul/2022 00:08:25.743]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:08:26.363]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:08:29.663]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[02/Jul/2022 00:08:29.663]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75614
[02/Jul/2022 00:08:38.265]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:08:38.265]WARNING [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 400 34
[02/Jul/2022 00:08:44.519]ERROR [django.request:224] Internal Server Error: /api/v1/user/campaing
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 511, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 423, in finalize_response
    assert isinstance(response, HttpResponseBase), (
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'bool'>`
[02/Jul/2022 00:08:44.520]ERROR [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 500 75614
[02/Jul/2022 00:09:16.309]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:09:16.944]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:09:39.378]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[02/Jul/2022 00:09:40.004]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:09:54.330]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:09:54.946]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:10:16.378]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[02/Jul/2022 00:10:16.996]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:10:21.945]INFO [django.server:161] "GET /api/v1/user/campaing HTTP/1.1" 200 1016
[02/Jul/2022 00:17:42.978]INFO [django.utils.autoreload:251] /usr/src/app/campaings/urls.py changed, reloading.
[02/Jul/2022 00:17:43.592]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:18:23.273]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:18:23.900]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:19:01.587]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[02/Jul/2022 00:19:02.209]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:19:14.487]WARNING [django.request:224] Bad Request: /api/v1/user/campaing/all/23
[02/Jul/2022 00:19:14.487]WARNING [django.server:161] "GET /api/v1/user/campaing/all/23 HTTP/1.1" 400 73
[02/Jul/2022 00:19:40.948]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:19:41.567]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:19:52.849]INFO [django.utils.autoreload:251] /usr/src/app/campaings/views.py changed, reloading.
[02/Jul/2022 00:19:53.476]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:19:57.349]INFO [django.server:161] "GET /api/v1/user/campaing/all/23 HTTP/1.1" 200 1016
[02/Jul/2022 00:20:09.432]INFO [django.server:161] "POST /api/v1/user/campaing HTTP/1.1" 201 36
[02/Jul/2022 00:20:19.651]INFO [django.server:161] "GET /api/v1/user/campaing/all/23 HTTP/1.1" 200 1513
[02/Jul/2022 00:20:46.532]INFO [django.utils.autoreload:251] /usr/src/app/campaings/urls.py changed, reloading.
[02/Jul/2022 00:20:47.155]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:22:45.265]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:22:45.700]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:22:45.982]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:24:30.240]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:24:30.679]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:24:30.963]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:28:13.730]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:28:14.171]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:28:14.456]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:31:54.113]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:31:54.556]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:31:54.844]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:34:46.721]INFO [django.utils.autoreload:251] /usr/src/app/core/campaing.py changed, reloading.
[02/Jul/2022 00:34:47.397]INFO [django.utils.autoreload:637] Watching for file changes with StatReloader
[02/Jul/2022 00:36:19.784]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:36:20.225]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:36:20.509]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:51:22.227]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:51:22.667]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:51:22.953]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:52:05.781]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:52:06.220]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:52:06.501]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:53:33.473]WARNING [django.request:224] Not Found: /9003api/v1/user/campaing
[02/Jul/2022 00:53:33.911]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:53:34.195]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:54:38.376]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:54:38.655]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:55:11.698]WARNING [django.request:224] Not Found: /9003api/v1/user/campaing
[02/Jul/2022 00:55:12.138]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:55:12.425]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:56:21.405]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:56:21.847]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:56:22.135]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:58:09.977]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 00:58:10.417]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 00:58:10.701]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:01:13.576]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:01:13.857]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:01:55.437]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:01:55.716]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:02:39.939]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:02:40.212]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:02:58.232]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:02:58.512]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:03:23.406]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:03:23.687]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:03:44.249]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:03:44.530]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:04:10.150]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:04:10.431]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:04:52.780]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:04:53.059]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:05:20.464]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 01:05:20.895]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:05:21.170]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:06:03.889]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 01:06:04.324]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:06:04.603]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:07:04.034]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:07:04.314]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:07:20.798]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:07:21.069]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:07:44.508]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:07:44.788]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:11:52.061]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:11:52.337]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:12:33.145]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:12:33.421]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:15:37.196]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:15:37.475]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:15:59.230]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:15:59.504]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:16:12.671]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:16:12.951]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:17:53.475]WARNING [django.request:224] Bad Request: /api/v1/user/campaing
[02/Jul/2022 01:17:53.978]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:17:54.252]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:18:26.328]WARNING [django.request:224] Bad Request: /api/v1/user
[02/Jul/2022 01:18:26.600]WARNING [django.request:224] Bad Request: /api/v1/user
